sudo: required

language: python
python: '2.7'

env:
  - distribution: centos
    version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""

services:
  - docker


before_install:
   # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  # Customize container
  - 'sudo docker build --rm=true --file=docker/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible docker'

script:
  - container_id=$(mktemp)

  # Symlink travis repo download to same place as ran inside the container
  - ln -s /tmp/scrapy-cluster ${PWD}

  # Run container in detached state
  - sudo docker run --detach --volume="${PWD}":/tmp/scrapy-cluster:rw ${run_opts} ${distribution}-${version}:ansible "${init}" > "${container_id}"

  # Ansible syntax check.
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm /bin/bash -c "ansible-playbook -i /tmp/scrapy-cluster/ansible/travis.inventory /tmp/scrapy-cluster/ansible/scrapy-cluster.yml --syntax-check"

  # Ansible install playbook.
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm /bin/bash -c "ansible-playbook -i /tmp/scrapy-cluster/ansible/travis.inventory /tmp/scrapy-cluster/ansible/scrapy-cluster.yml --connection=local --become"

  # Install coverall and other pip requiremnts
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm /bin/bash -c "virtualenv /tmp/sc; source /tmp/sc/bin/activate; pip install -r /tmp/scrapy-cluster/requirements.txt; cd /tmp/scrapy-cluster; find . -name "*.pyc" -type f -delete; cd utils; python setup.py install;"

  # Run offline test
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm /bin/bash -c "source /tmp/sc/bin/activate; cd /tmp/scrapy-cluster; ./run_offline_tests.sh"

  # Run Online test
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm /bin/bash -c "source /tmp/sc/bin/activate; cd /tmp/scrapy-cluster; ./run_online_tests.sh"

  # Run Coveralls Report
  - pip install coveralls; coveralls

  # Stop Docker Containers
  - sudo docker stop "$(cat ${container_id})"

notifications:
  slack:
    rooms:
      secure: nPY+SvgkOrpvU76i55bDtXPbclq7WzY2DCwOCbYNzpMMTNnlqV9uhwUc31gHdl+xO8aXf52JwuOqTZnJTi9PGuomp7qf4N4z/dz3tKdjj3ppgeDx8hcmAikiM/qoOUadA9zNvP+wHfJSK7l6LnbAZgdOAXZb77Fk5rIuRr695vg=
    on_success: always
    on_failure: always
    on_start: always
